apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-trut
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/susdas_quay_org/mvp-dev-rfpn-tenant/mvp-test-app/test-mvp-component-trut@sha256:c6db8d814f419e602a53f9e80d13e2fe811019f865f8f6f21654c422c9aa9222
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
